image: registry.gitlab.com/pages/hugo/hugo_extended:latest

pages:
  stage: deploy
  script:
    - hugo --baseURL "${CI_PAGES_URL}/" --minify
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
